version = 0.1
[default.deploy.parameters]
stack_name = "bookverse"
resolve_s3 = true
s3_prefix = "bookverse"
region = "us-east-1"
profile = "uniandes"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
